#!/usr/bin/env python
"""
https://github.com/lathama/python-testing-example
"""
import sys
sys.dont_write_bytecode = True

import testingdemo

print("\nThe testingdemo version is: " + testingdemo.__version__ + "\n")
